services:

  # PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: trainee-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TIGER
      POSTGRES_DB: traineedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trainee-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d traineedb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: trainee-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - trainee-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Spring Boot App
  app:
    image: chirag1804/trainee-api:latest
    container_name: trainee-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/traineedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TIGER
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8081
    depends_on:
      db:
        condition: service_healthy
    networks:
      - trainee-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  trainee-network:
    driver: bridge
