# =============================================
# Local SonarQube Configuration
# =============================================
sonar.projectKey=traineeAPI
sonar.projectName=traineeAPI
sonar.projectVersion=0.0.1-SNAPSHOT

# Host
sonar.host.url=http://localhost:9000

# Source paths
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.language=java
