#spring.application.name=traineeAPI
#spring.datasource.url=jdbc:postgresql://localhost:5432/SpringBootDB
#spring.datasource.username=postgres
#spring.datasource.password=TIGER

#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

#server.port=8081


# Server
server.port=8081

# PostgreSQL — 'db' = service name in docker-compose
spring.datasource.url=jdbc:postgresql://db:5432/traineedb
spring.datasource.username=${POSTGRES_USER:trainee_user}
spring.datasource.password=${POSTGRES_PASSWORD:trainee_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App Name
spring.application.name=traineeAPI
